name: Run k6 Load Test
run-name: "k6 Load Test | ${{ inputs.environment }} | ${{ inputs.test_file }}"
permissions:
    contents: read
on:
    workflow_call:
        inputs:
            environment:
                type: string
                description: Environment
                required: true
            test_file:
                type: string
                description: Test file in load-test/src/tests, comma separated if multiple files
                required: true
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Environment
                options:
                    - syst
                    - dev
                default: syst
                required: true
            test_file:
                type: string
                description: Test file in load-test/src/tests, comma separated if multiple files
                default: averageTest/average-bifPopulateQueueApi.ts,averageTest/average-bifProcessQueueApi.ts
                required: true

jobs:
    k6_load_test:
        name: k6 Load Test
        runs-on: "ubuntu-latest"
        environment: ${{ inputs.environment }}
        concurrency:
            group: k6-load-test-${{ inputs.environment }}
        steps:
            - name: Checkout code
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5   # v4
            - uses: grafana/setup-k6-action@ffe7d7290dfa715e48c2ccc924d068444c94bde2   # v1
              with:
                  k6-version: 0.56.0
                  browser: true
            - name: Format test file paths
              id: format_paths
              run: |
                  echo "${{ inputs.test_file }}" | tr ',' '\n' | sed 's|^|load-test/src/tests/|' > formatted_paths.txt
                  echo "FORMATTED_PATH<<EOF" >> $GITHUB_ENV
                  cat formatted_paths.txt >> $GITHUB_ENV
                  echo "EOF" >> $GITHUB_ENV
            - name: Run k6 Load Test
              uses: grafana/run-k6-action@a15e2072ede004e8d46141e33d7f7dad8ad08d9d   # v1
              with:
                  cloud-run-locally: true 
                  parallel: true
                  path: |
                      ${{ env.FORMATTED_PATH }}
                  flags: -e LOAD_TEST_RUNNER_CLIENT_SECRET=${{ secrets.LOAD_TEST_RUNNER_CLIENT_SECRET }} -e TEST_RUNNER_ENV=${{ inputs.environment }} -e LOAD_TEST_SUBSCRIBER_CLIENT_SECRETS=${{ secrets.LOAD_TEST_SUBSCRIBER_CLIENT_SECRETS }} -e LOAD_TEST_USER_PASSWORD=${{ secrets.LOAD_TEST_USER_PASSWORD }}
              env:
                  K6_COMPATIBILITY_MODE: experimental_enhanced
                  TEST_RUNNER_ENV: ${{ inputs.environment }}
