name: E2E Test Template
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      app:
        type: string
        description: "The app to run tests against"
        required: true
      environment:
        type: string
        description: "The environment to run tests against"
        required: true
      upload_artifacts:
        type: boolean
        description: "Whether to upload artifacts to report"
        required: true
        default: false
      upload_to_github_pages:
        type: boolean
        description: "Whether to upload the report to github pages (main always uploads)"
        required: true
        default: false
      agent-os:
        type: string
        description: "What OS to run the tests on"
        required: true
        default: "ubuntu-22.04"
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - uat
          - preprod
        default: uat
        required: true
      options:
        type: string
        description: "Additional options to pass to the test command"
        required: false
        default: ""
      app:
        type: choice
        description: "The app to run tests against"
        options:
          - dtp
        default: dtp
        required: true
      upload_artifacts:
        type: choice
        description: "Whether to upload artifacts to report"
        required: true
        options:
          - "true"
          - "false"
        default: "true"
      upload_to_github_pages:
        type: choice
        description: "Whether to upload the report to github pages (main always uploads)"
        required: true
        options:
          - "true"
          - "false"
        default: "false"
      agent-os:
        type: choice
        description: "What OS to run the tests on"
        required: true
        options:
          - "ubuntu-22.04"
          - "macos-latest"
        default: "ubuntu-22.04"
jobs:
  e2e_test:
    runs-on: ${{ inputs.agent-os }}
    environment: ${{ inputs.environment || github.event.inputs.environment }}
    timeout-minutes: 60
    concurrency:
      group: e2e-${{ inputs.app || github.event.inputs.app }}-${{ inputs.environment || github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Exit if no e2e test
        if: ${{ steps.variables.outputs == 'path-doesnt-exist' }}
        run: |
          echo "No e2e test for ${{ inputs.app }}"
          exit 1
      - name: Project Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          dest: ./e2e/
      - name: Setup Playwright
        uses: ./.github/actions/setup-playwright
      - name: Run Playwright tests
        id: test_run
        env:
          DTP_ROOT_URL: ${{ vars.DTP_ROOT_URL }}
          AF_ROOT_URL: ${{ vars.AF_ROOT_URL }}
          E2E_DTP_FORM_NAME: ${{ vars.E2E_DTP_FORM_NAME }}
          TC_SERVICE_BASE_URL: ${{ vars.TC_SERVICE_BASE_URL }}
          TEST_RUNNER_ENV: ${{ 'preprod' }}
          E2E_TEST_RUNNER_CLIENT_ID: ${{ vars.E2E_TEST_RUNNER_CLIENT_ID }}
          E2E_TEST_RUNNER_CLIENT_SECRET: ${{ secrets.E2E_TEST_RUNNER_CLIENT_SECRET }}
          E2E_TEST_USER_EMAIL: ${{ vars.E2E_TEST_USER_EMAIL }}
          E2E_TEST_RUNNER_PASSWORD: ${{ secrets.E2E_TEST_RUNNER_PASSWORD}}
          E2E_TEST_RUNNER_ENV: ${{ vars.E2E_TEST_RUNNER_ENV}}
          E2E_DTP_GAPI_URL: ${{ vars.E2E_DTP_GAPI_URL }}
          E2E_SUBSCRIBER_CLIENT_ID: ${{ vars.E2E_SUBSCRIBER_CLIENT_ID }}
          E2E_SUBSCRIBER_CLIENT_SECRET: ${{ secrets.E2E_SUBSCRIBER_CLIENT_SECRET }}
          E2E_TEST_USER_IDS: ${{ vars.E2E_TEST_USER_IDS }}
          AF_E2E_TEST_USER_IDS: ${{ vars.AF_E2E_TEST_USER_IDS }}
          ATTACHMENT_S3_BUCKET_URL: ${{ vars.ATTACHMENT_S3_BUCKET_URL}}
          AGENCY_NAME: ${{'https://forms.preprod.beta.my.qld.gov.au/companioncardapply'}}
          
        run: |
          cd ./e2e/
          # Do not stop the script immediately if the test command fails
          # We want to capture the test result and set E2E_TEST_OUTCOME accordingly
          set +e
          pnpm run test --pass-with-no-tests ${{ inputs.options }}
          exit_code=$?
          set -e
          if [ "$exit_code" -eq 0 ]; then
            echo "E2E_TEST_OUTCOME=PASS" >> $GITHUB_ENV
          else
            echo "E2E_TEST_OUTCOME=FAIL" >> $GITHUB_ENV
          fi
          exit $exit_code
      - name: Upload Test Artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always() && (inputs.upload_artifacts == true || inputs.upload_artifacts == 'true')
        with:
          name: playwright-test-results
          path: ./e2e/test-results
          retention-days: 7
      - name: Publish Test Result To Queue
        if: always()
        env:
          E2E_DTP_GAPI_URL: ${{ 'https://www.preprod.graph.qld.gov.au/graphql' }}
          E2E_SUBSCRIBER_CLIENT_ID: ${{ 'app-queenslandonline-cardsandconcessions-subscriber-PREPROD-1750631735627'}}
          E2E_SUBSCRIBER_CLIENT_SECRET: ${{ 'cDODlqUVPC2pn5H1Xn0pf4X0gDxjx2mK'}}
          E2E_TEST_RUNNER_ENV: ${{ 'preprod' }}
          E2E_DTP_FORM_NAME: ${{ 'CC Apply' }}
          E2E_TEST_OUTCOME: ${{ env.E2E_TEST_OUTCOME }}
        run: |
          echo "E2E_TEST_OUTCOME is: $E2E_TEST_OUTCOME"
          $GITHUB_WORKSPACE/.github/scripts/publish-test-result-to-queue.sh
